repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        types: [ python ]
        args: [ --line-length=88, --target-version=py311 ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --exclude=deprecated,
               --exclude=venv, --install-types, --non-interactive]
        fail_fast: true

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        name: reorder-python-imports
        entry: reorder-python-imports
        language: python
        types: [ python ]
        fail_fast: true

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]
        fail_fast: true

